[package]
name = "pp_client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = "4.5.16"
mio = { version = "1.0.2", features = ["net", "os-poll"] }
private_poker = { path = "../private_poker" }
ratatui = "0.28.0"
