[package]
name = "private_poker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bincode = "1.3.3"
crossbeam-channel = "0.5.13"
mio = "1.0.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.63"
