name: Continuous integration

on:
  push:
    branches:
      - main
        
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt
  
      - name: Lint
        run: |
          cargo clippy -- -D warnings
          cargo fmt --all -- --check
  
      - name: Test
        run: cargo test

      - name: Debug build
        run: cargo build
